apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-benchmarking-postgres
spec:
  selector:
    app: {{ .Release.Name }}-benchmarking-postgres
  ports:
    - port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simulation-postgres
spec:
  selector:
    app: {{ .Release.Name }}-simulation-postgres
  ports:
    - port: 5432
