apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-benchmarking-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-benchmarking-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-benchmarking-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-benchmark-api-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-benchmark-api-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.global.postgresql.benchmarking.database }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-simulation-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-simulation-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-simulation-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-simulation-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-simulation-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.global.postgresql.simulation.database }}
