apiVersion: v1
kind: Service
metadata:
  name: simulation-postgres
  labels:
    app: simulation-postgres
spec:
  type: NodePort
  selector:
    app: simulation-postgres
  ports:
    - port: 5433
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-postgres
  template:
    metadata:
      labels:
        app: simulation-postgres
    spec:
      containers:
        - name: simulation-postgres
          image: postgres:14.2-alpine
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: simulation-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simulation-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: simulation_db
