apiVersion: v1
kind: Service
metadata:
  name: simulation-rabbitmq
  labels:
    app: simulation-rabbitmq
spec:
  selector:
    app: simulation-rabbitmq
  ports:
    - port: 5672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-rabbitmq
spec:
  selector:
    matchLabels:
      app: simulation-rabbitmq
  template:
    metadata:
      labels:
        app: simulation-rabbitmq
    spec:
      containers:
        - name: simulation-rabbitmq
          image: rabbitmq:4.0.1-alpine
          ports:
            - containerPort: 5672
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: simulation-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: simulation-secrets
                  key: RABBITMQ_PASSWORD
