apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-simulation-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.postgresql.simulation.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.simulation.password | b64enc }}
  RABBITMQ_USER: {{ .Values.global.rabbitmq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.password | b64enc }}
  RABBITMQ_QUEUE: {{ .Values.global.rabbitmq.queue | b64enc }}