apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-benchmark-api-secrets
type: Opaque
data:
  api-key: {{ .Values.benchmarkApi.apiKey | b64enc }}
  postgres-user: {{ .Values.global.postgresql.benchmarking.username | b64enc }}
  postgres-password: {{ .Values.global.postgresql.benchmarking.password | b64enc }}
