apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-benchmark-api
  labels:
    app: {{ .Release.Name }}-benchmark-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Release.Name }}-benchmark-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
